### ISSUE TITLE
第3章 使用ambari安装Hadoop集群的几个问题

### ISSUE THREAD

**Issue by springfred** [nauu/bigdatabook#3]
1. P47页 2.5.5容错章节, “有据复制和恢复日志”, 少了一个“数”; 应该是“有数据复制和恢复日志”
2. Ambari-Server存在单点问题, 如何解决?
3. P58页 表3-1 集群服务规划设计表格里的主控服务只规划了一台主机, 没有单点问题?

**Comment by nauu** [comment]
1.感谢提供的勘误信息
2.AmbariServer目前没有官方提供的高可用方案，这一块相对于服务而言简单一些。可以做好数据库的备份
3.相应服务的主控节点都有HA， 可以在Ambari中设置，比如HDFS的Namenode等
